print("Hello, world!")
print("My name is Shreyansh")
print("I am learning coding step by step")
print("2 + 2 =", 2 + 2)
print("5 * 3 =", 5 * 3)
print("10 / 2 =", 10 / 2)
print("8 - 4 =", 8 - 4)
print("I love programming!")
print("Python is fun!")
print("Let's code more!")
print("Goodbye, world!")
name = input("What is your name? ")
age = input("How old are you? ")

print("Hello", name)
print("You are", age, "years old")
